-- phpMyAdmin SQL Dump
-- version 4.2.11
-- http://www.phpmyadmin.net
--
-- Host: 127.0.0.1
-- Generation Time: Apr 23, 2015 at 01:59 AM
-- Server version: 5.6.21
-- PHP Version: 5.6.3

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `education`
--

-- --------------------------------------------------------

--
-- Table structure for table `education`
--

CREATE TABLE IF NOT EXISTS `education` (
`id` int(5) NOT NULL,
  `title` text CHARACTER SET latin1 NOT NULL,
  `description` text CHARACTER SET latin1 NOT NULL,
  `lesson_link` text CHARACTER SET latin1 NOT NULL,
  `lesson_image` text CHARACTER SET latin1 NOT NULL,
  `category` varchar(200) CHARACTER SET latin1 NOT NULL,
  `student_grades` set('1','2','3','4','5','6','7','8','9','10','11','12','k') CHARACTER SET latin1 NOT NULL,
  `author` text CHARACTER SET latin1 NOT NULL,
  `content_type` text CHARACTER SET latin1 NOT NULL,
  `time_scraped` datetime NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=143 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Dumping data for table `education`
--

INSERT INTO `education` (`id`, `title`, `description`, `lesson_link`, `lesson_image`, `category`, `student_grades`, `author`, `content_type`, `time_scraped`) VALUES
(1, 'Conic Flyer\n', 'Manipulate different types of conic section equations on a coordinate plane using slider bars. Learn how each constant and coefficient affects the resulting graph. Choose from vertical or horizontal parabola, circle, ellipse, and vertical or horizontal hyperbola.\n', 'http://www.shodor.org/interactivate/activities/ConicFlyer/\n', 'http://www.shodor.org/media/Z/T/k/0ZjZkNTRhNmU5N2MwZTRjZWI1N2YyNWI5OWFlNmY.gif\n', 'graphs,algebra,geometry\n', '9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(2, 'Two Variable Function Pump\n', 'Enter two complex numbers (z and c) as ordered pairs of real numbers, then click a button to iterate step by step. The iterates are graphed in the x-y plane and printed out in table form. This is an introduction to the idea of prisoners/escapees in iterated functions and the calculation of fractal Julia sets.\n', 'http://www.shodor.org/interactivate/activities/TwoVariableFunction/\n', 'http://www.shodor.org/media/N/T/E/3MjdmNDg3YWZkNWQwNjkyZGNlNDY2NTcwMDA4Y2M.gif\n', 'number and operations,graphs,algebra,geometry\n', '6,7,8,9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(3, 'Caesar Cipher III\n', 'Decode encrypted messages to determine the form for an affine cipher, and practice your reasoning and arithmetic skills. Input your guesses for the multiplier and constant. Caesar Cipher III is one of the Interactivate assessment explorers.\n', 'http://www.shodor.org/interactivate/activities/CaesarCipherThree/\n', 'http://www.shodor.org/media/M/D/I/yNDk0NTI4ZmM0MDc5MGVmNzJhOTM4N2IyMjM1ZTk.gif\n', 'discrete,number and operations,algebra\n', '6,7,8,9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(4, 'Rabbits and Wolves\n', 'Experiment with a simple ecosystem consisting of grass, rabbits, and wolves, learning about probabilities, chaos, and simulation.\n', 'http://www.shodor.org/interactivate/activities/RabbitsAndWolves/\n', 'http://www.shodor.org/media/Y/W/I/yYjVkNmQ1MzdkMTU2MDA3ZGI3OWI2NWNlMjAxYTA.gif\n', 'graphs,modeling,probability,calculus,statistics\n', '3,4,5,6,7,8,9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(5, 'Algebra Four\n', 'Students play a generalized version of connect four, gaining the chance to place a piece on the board by solving an algebraic equation. Parameters: Level of difficulty of equations to solve and type of problem. Algebra Four is one of the Interactivate assessment games.\n', 'http://www.shodor.org/interactivate/activities/AlgebraFour/\n', 'http://www.shodor.org/media/N/2/R/mYTRjMWQ3NmE1ZjFjZjQ1Y2M4ZjgzNzY1NjhlZTk.gif\n', 'algebra\n', '6,7,8,9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(6, 'Surface Area and Volume\n', 'Manipulate dimensions of polyhedra, and watch how the surface area and volume change. Parameters: Type of polyhedron, length, width and height. Surface Area and Volume one of the Interactivate assessment explorers.\n', 'http://www.shodor.org/interactivate/activities/SurfaceAreaAndVolume/\n', 'http://www.shodor.org/media/M/W/Q/yNzIxNmNiYzFiZWNmMjQ1YWQ2YTJlOWQ1NjA2NjU.gif\n', 'geometry\n', '3,4,5,6,7,8,9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(7, 'Stopwatch\n', 'Functions like a real stopwatch, recording times that you choose. This stopwatch is accurate to the nearest tenth of a second. Parameters: Count up from 0 or count down from a set time.\n', 'http://www.shodor.org/interactivate/activities/Stopwatch/\n', 'http://www.shodor.org/media/Y/m/Q/wODA0NjY5Y2Q3ZjkzMTRkODM3NGRlMDNkY2FkZDE.gif\n', 'geometry\n', '3,4,5,6,7,8,9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(8, 'Simple Monty Hall\n', 'Choose one of three doors to experimentally determine the odds of winning the grand prize behind one of the doors, as in the TV program "Let''s Make a Deal." Parameters: Staying or switching between the two remaining doors.\n', 'http://www.shodor.org/interactivate/activities/SimpleMontyHall/\n', 'http://www.shodor.org/media/N/T/J/iYzAyYzEyYzkzN2NkY2E0MDFiMTY5NzkzODZjODA.gif\n', 'discrete,probability\n', '6,7,8,9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(9, 'Julia Sets\n', 'Enter a complex value for "c" in the form of an ordered pair of real numbers. The applet draws the fractal Julia set for that seed value.\n', 'http://www.shodor.org/interactivate/activities/JuliaSets/\n', 'http://www.shodor.org/media/Y/W/I/xMzVhZWE3NWM1MTRiMTllYjMxNzFhN2FkODNlNTc.gif\n', 'discrete,number and operations,geometry,fractions\n', '6,7,8,9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(10, 'A Better Fire!!\n', 'Students run a simulation of how a fire will spread through a stand of trees, learning about probability and chaos. Parameters: Forest density, wind direction, size of forest.\n', 'http://www.shodor.org/interactivate/activities/ABetterFire/\n', 'http://www.shodor.org/media/N/z/c/xOWQ5NDViYTBiMWM4MzMxN2NjY2MwNTUxZjc3ODY.gif\n', 'discrete,modeling,probability,fractions\n', '6,7,8,9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(11, 'Converter\n', 'Converts fractions to decimals and decimals to fractions. Observe the relationships between fractions and decimals.\n', 'http://www.shodor.org/interactivate/activities/Converter/\n', 'http://www.shodor.org/media/M/W/J/jMTYxNGY4NjFjY2RlMTE3ZTZmM2ZiMDQ1YjA1MzQ.gif\n', 'number and operations,fractions\n', '3,4,5,6,7,8,9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(12, 'Algebra Quiz\n', 'Test your algebra skills by answering questions. This quiz asks you to solve algebraic linear and quadratic equations of one variable. Choose difficulty level, question types, and time limit. Algebra Quiz is one of the Interactivate assessment quizzes.\n', 'http://www.shodor.org/interactivate/activities/AlgebraQuiz/\n', 'http://www.shodor.org/media/N/T/Q/4ODgxZTJhYjJiY2E3ZjI2MjExN2I0ZjEzM2NjMDQ.gif\n', 'algebra\n', '6,7,8,9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(13, 'Perimeter Explorer\n', 'Learn the relationship between perimeter and area. A shape will be automatically generated with the area that you choose. Calculate the perimeter of this shape. Perimeter Explorer is one of the Interactivate assessment explorers.\n', 'http://www.shodor.org/interactivate/activities/PerimeterExplorer/\n', 'http://www.shodor.org/media/Y/j/Q/xN2YyOWIzMTM2ZTU0ODA2N2VlNWE0NWMxYTE0ZjM.gif\n', 'geometry\n', '3,4,5,6,7,8', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(14, 'Generalized Monty Hall\n', 'Run a simulation to generate results from running the Monty Hall for multiple trials. This is similar to the game show "Let''s Make A Deal", where you choose one of N doors in hopes of finding a grand prize behind one of the doors. Parameters: Number of doors, number of trials, staying, or switching between the two remaining doors.\n', 'http://www.shodor.org/interactivate/activities/GeneralizedMontyHall/\n', 'http://www.shodor.org/media/O/W/E/5YmZjNjRlYjc2NDAzYzI5YmVhNDM0NjUyYzE5MTc.gif\n', 'discrete,modeling,probability\n', '6,7,8,9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(15, 'Order of Operations Four\n', 'Students play a generalized version of connect four, gaining the chance to place a piece on the board by answering order of operations questions (addition/subtraction, multiplication/division, exponents, and parentheses). Parameters: time, difficulty level, types of questions. Order of Operations Four is one of the Interactivate assessment games.\n', 'http://www.shodor.org/interactivate/activities/OrderOfOperationsFou/\n', 'http://www.shodor.org/media/N/D/Q/4ZDc4ZDhjM2IyN2Q2NGRlMjZjMGVmZGZkODY4Yjk.gif\n', 'number and operations\n', '3,4,5,6,7,8,9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(16, 'Measures\n', 'Enter data and view the mean, median, variance, and standard deviation of the data set. Parameters: Number of observations, range for observations, which statistics to view, identifiers for the data.\n', 'http://www.shodor.org/interactivate/activities/Measures/\n', 'http://www.shodor.org/media/N/W/Y/zNDQyMDc3MDFmOWFjMTJiMWVkNjdkMzQ5ZWQwNTQ.gif\n', 'statistics\n', '3,4,5,6,7,8,9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(17, 'Bar Graph Sorter\n', 'Sort colored shapes into a bar graph. Practice sorting by shape or by color. Appropriate for elementary grades. Bar Graph Sorter is one of the Interactivate assessment explorers.\n', 'http://www.shodor.org/interactivate/activities/BarGraphSorter/\n', 'http://www.shodor.org/media/Z/m/E/5NWM3MmQ4MDEzMTE4NWYwYjZmZTExM2FjMDUzZDE.gif\n', 'graphs,geometry,statistics\n', '3,4,5,6,7,8', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(18, 'Advanced Fire\n', 'Run a simulation of how a fire spreads through a stand of trees, learning about probability and chaos. Track the results of multiple burns and use the data to draw conclusions.\n', 'http://www.shodor.org/interactivate/activities/AdvancedFire/\n', 'http://www.shodor.org/media/Z/T/E/yODVjNmUxN2VhODU1NTg2N2M0MGIxNzRmNTQ3YjE.gif\n', 'modeling,probability,statistics\n', '6,7,8,9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(19, 'Tortoise and Hare Race\n', 'Step through the tortoise and hare race, based on Zeno''s paradox, to learn about the multiplication of fractions and about convergence of an infinite sequence of numbers.\n', 'http://www.shodor.org/interactivate/activities/Tortoise/\n', 'http://www.shodor.org/media/Z/G/Q/2N2M5ZTVkZjQ4MDJmNDZjZGU2Yjk5YTMzYTZhYzE.gif\n', 'discrete,number and operations\n', '3,4,5,6,7,8', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(20, 'Fractal Dimensions\n', 'Determine the fractal dimensions of several line-deformation fractals. Input the scale factor and number of similar copies, and the dimension will be calculated. Fractal Dimensions is one of the Interactivate assessment explorers.\n', 'http://www.shodor.org/interactivate/activities/FractalDimensions/\n', 'http://www.shodor.org/media/N/j/N/hZDQ4MzBkMmY2MWM2MTdhYWFlOGYzMGIxZDI4MjA.gif\n', 'discrete,number and operations,geometry\n', '6,7,8,9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(21, 'Bar Graph\n', 'Enter data to create a bar graph, then change many settings for the graph''s appearance.\n', 'http://www.shodor.org/interactivate/activities/BarGraph/\n', 'http://www.shodor.org/media/N/z/h/hNWQ4OTBiY2ZjNTU4MGRmNTUxMDk4YTZjMWEwYmI.gif\n', 'graphs,statistics\n', '3,4,5,6,7,8,9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(22, 'Estimator\n', 'Practice estimation skills by determining the number of objects, the length of a line, or the area of a shape. Parameters: error tolerance of estimate. Estimator is one of the Interactivate assessment explorers.\n', 'http://www.shodor.org/interactivate/activities/Estimator/\n', 'http://www.shodor.org/media/O/D/U/0Yzk2YWEwMTdlMmM3MjBlZWM2OGVkZDRiYWQ4Zjk.gif\n', 'number and operations\n', '3,4,5,6,7,8,9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(23, 'Derivate\n', 'View the graph and the equation of the line tangent to any function at any point on the function.\n', 'http://www.shodor.org/interactivate/activities/Derivate/\n', 'http://www.shodor.org/media/M/D/k/zYjYxMTE1NDM3ZjVkZGY2MDZjZGYyYjE3ZDBlYjQ.gif\n', 'algebra,calculus\n', '9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(24, 'Overlapping Gaussians\n', 'In this applet you can adjust the parameters on two Gaussian curves to determine if there is a possibility of a difference between the two means.\n', 'http://www.shodor.org/interactivate/activities/OverlappingGaussians/\n', 'http://www.shodor.org/media/Y/2/I/4Y2IxZWQzZjU2MTAwNThjYTk5YTAyMTliYTM3NjI.png\n', 'probability,statistics\n', '9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(25, 'Racing Game with One Die\n', 'Simulate a game where two players each roll a die, and the lucky player moves one step to the finish. Parameters: what rolls win and how many steps to the finish line.\n', 'http://www.shodor.org/interactivate/activities/RacingGameWithOneDie/\n', 'http://www.shodor.org/media/N/j/N/kNjY0OTQ2YTM1ZDUzMGM1NmQxYjFhMmY5Y2YwZjg.gif\n', 'discrete,probability\n', '3,4,5,6,7,8,9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(26, 'Floor Tiles\n', 'Build a "floor tile" by dragging the corners of a quadrilateral. Learn about tessellation of quadrilateral figures when the shape you built is tiled over an area.\n', 'http://www.shodor.org/interactivate/activities/FloorTiles/\n', 'http://www.shodor.org/media/O/D/N/mNjkxYTViZGI2MTlmY2E3NDA3ZDhiZDkyZWVkOGQ.gif\n', 'geometry\n', '3,4,5,6,7,8,9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(27, 'More or Less Estimator\n', 'Practice estimation skills by determining whether the number of objects, the length of a line, or the area of a shape is more or less than the number given. Parameters: error tolerance of estimate. More or Less Estimator is one of the Interactivate assessment explorers.\n', 'http://www.shodor.org/interactivate/activities/MoreOrLessEstimator/\n', 'http://www.shodor.org/media/Y/z/A/xMGY4M2MwZmQ4YjE0YjZkMGU4NmYzNTEzMmNiNzk.gif\n', 'number and operations\n', '3,4,5,6,7,8,9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(28, 'Buffon''s Needle\n', 'Experiment with a simulation to get an approximation of Pi by dropping a needle on a lined sheet of paper.\n', 'http://www.shodor.org/interactivate/activities/Buffon/\n', 'http://www.shodor.org/media/O/D/M/zN2UwOTI1Mzc3MGFhYThlZTJjZTQxMjI5NDJjZTc.gif\n', 'discrete,probability,statistics\n', '6,7,8,9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(29, 'Single Fraction Pointer\n', 'Determine the value of a given fraction represented as a point on a number line. Then find a fraction whose value is the given fraction using an arrow on the number line as a guide. Single Fraction Pointer is one of the Interactivate assessment explorers.\n', 'http://www.shodor.org/interactivate/activities/SingleFractionPoint/\n', 'http://www.shodor.org/media/N/D/g/1ZTgzZDE3Nzg5MzRiMjIwNmUwZGNiNmU4NWZmODM.gif\n', 'number and operations,fractions\n', '3,4,5,6,7,8', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(30, 'Linear Function Machine\n', 'Students investigate linear functions by trying to guess the slope and intercept from inputs and outputs. Linear Function Machine is one of the Interactivate assessment explorers.\n', 'http://www.shodor.org/interactivate/activities/LinearFunctMachine/\n', 'http://www.shodor.org/media/M/T/E/5NjcyZTM3ZGEzZGYwZjhhOTJiNGQ1ZDg2MDNhODY.gif\n', 'discrete,algebra\n', '6,7,8,9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(31, 'Estimator Quiz\n', 'Test your estimation skills by answering questions. This quiz asks you to estimate the answer to addition, multiplication, and percentage questions. Choose difficulty level, question types, and time. Estimator Quiz is one of the Interactivate assessment quizzes.\n', 'http://www.shodor.org/interactivate/activities/EstimatorQuiz/\n', 'http://www.shodor.org/media/M/z/U/3OWNkOTcyYzkyMGUxY2YzZGYwZTdiZTc0MjhhY2Q.gif\n', 'number and operations\n', '3,4,5,6,7,8,9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(32, 'Simple Maze Game\n', 'Investigate the first quardant of the Cartesian coordinate system by directing a robot through a mine field laid out on the grid. Simple Maze Game is one of the Interactivate assessment explorers.\n', 'http://www.shodor.org/interactivate/activities/SimpleMazeGame/\n', 'http://www.shodor.org/media/M/G/Q/0ZmU0NzA1YTM5MWFhMjdiYmE1YTdlZDJhM2U3Mjg.gif\n', 'graphs,algebra,geometry\n', '3,4,5,6,7,8', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(33, 'Factorize 2\n', 'Visualize factors through building rectangular areas on a grid. As you draw each factor set on the grid, the factors will be listed. Factorize 2 is one of the Interactivate assessment explorers.\n', 'http://www.shodor.org/interactivate/activities/FactorizeTwo/\n', 'http://www.shodor.org/media/Z/T/k/1OGZmZGJiZmUxYmY5MTJkY2MzOGUzMzI0MTFjNGM.gif\n', 'discrete,number and operations,geometry,fractions\n', '3,4,5,6,7,8,9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(34, 'Shape Builder\n', 'This activity operates in one of two modes: auto draw and create shape mode, allowing you to explore relationships between area and perimeter. Shape Builder is one of the Interactivate assessment explorers.\n', 'http://www.shodor.org/interactivate/activities/ShapeBuilder/\n', 'http://www.shodor.org/media/Y/m/U/2NzllMmYxMzYzMDMzNDRiNDc4MWUxYWFmM2JkNDQ.gif\n', 'geometry\n', '3,4,5,6,7,8', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(35, 'Squaring the Triangle\n', 'Learn about how the Pythagorean Theorem works through investigating the standard geometric proof. Parameters: Sizes of the legs of the triangle.\n', 'http://www.shodor.org/interactivate/activities/SquaringTheTriangle/\n', 'http://www.shodor.org/media/M/G/E/zYWNiNGQ5ODA5YTUxNjZjODMzODZkZWZjODVlOTI.gif\n', 'geometry\n', '6,7,8,9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(36, 'Histogram\n', 'View histograms for built-in or user-specified data. Experiment with how the size of the class intervals influences the appearance of the histogram. Parameters: Data sets, class sizes.\n', 'http://www.shodor.org/interactivate/activities/Histogram/\n', 'http://www.shodor.org/media/N/z/Q/2YjFmMjdlMTQxNzIwMGRmN2FjY2E3YWE2Yjc4YTQ.gif\n', 'graphs,statistics\n', '3,4,5,6,7,8,9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(37, 'Caesar Cipher II\n', 'Encode and decode messages to determine the form for an affine cipher. Input a message to encode, then input your guesses for the constant and multiplier. Caesar Cipher II is one of the Interactivate assessment explorers.\n', 'http://www.shodor.org/interactivate/activities/CaesarCipherTwo/\n', 'http://www.shodor.org/media/Z/T/A/xMDYwZmE0MjNiMTdkNDM4YjAwMjk4MTliYzg4OWI.gif\n', 'discrete,number and operations,algebra\n', '6,7,8,9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(38, 'Coin Toss\n', 'Simulation of a coin toss allowing the user to input the number of flips. Toss results can be viewed as a list of individual outcomes, ratios, or table.\n', 'http://www.shodor.org/interactivate/activities/Coin/\n', 'http://www.shodor.org/media/Y/j/U/zOTU4MTkwMDFmMGE1OTQwOGFkOGEzZGIwNTFkYmQ.\n', 'discrete,probability,fractions,statistics\n', '3,4,5,6,7,8,9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(39, 'Angles\n', 'Practice your knowledge of acute, obtuse, and alternate angles. Also, practice relationships between angles - vertical, adjacent, alternate, same-side, and corresponding. Angles is one of the Interactivate assessment explorers.\n', 'http://www.shodor.org/interactivate/activities/Angles/\n', 'http://www.shodor.org/media/Z/D/k/0NGYwZjg2MTI0MTYwN2JmYzUxN2RjYjEyMmU2Y2Y.gif\n', 'geometry\n', '3,4,5,6,7,8,9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(40, 'Vertical Line Test\n', 'Learn about the vertical line test for functions by trying to connect points in the plane to build a function. When you have connected all of the points, you will be told if your graph is a valid graph of a function. Vertical Line Test is one of the Interactivate assessment explorers.\n', 'http://www.shodor.org/interactivate/activities/VerticalLineTest/\n', 'http://www.shodor.org/media/M/m/Q/4NTQ5ZGIxMzExNzMzNmUzNTM5NmE3NzlmMzMxNmY.gif\n', 'discrete,graphs,algebra\n', '6,7,8,9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(41, 'Crazy Choices Game\n', 'Compare theoretical and experimental probabilities, using dice, cards, spinners, or coin tosses. Three different probabilities can be compared at once. Parameters: Type of probabilities, number of trials.\n', 'http://www.shodor.org/interactivate/activities/CrazyChoicesGame/\n', 'http://www.shodor.org/media/M/m/R/jYzRiNGU0ZGJhNjZlMDAwYTcyNDUxM2Q2YmVmNmM.gif\n', 'discrete,probability,fractions,statistics\n', '6,7,8,9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(42, 'Multiple Linear Regression\n', 'Students compare multiple independent variables as predictors of one dependent variable. Students explore correlation and lines of best-fit.\n', 'http://www.shodor.org/interactivate/activities/MultipleLinearRegression/\n', 'http://www.shodor.org/media/Y/W/J/kNDY3NTczNTgxYjY4ZGNlNzIyZmY3MGUyNWRhYjA.gif\n', 'modeling,algebra,statistics\n', '9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(43, 'Simple Coordinates Game\n', 'Investigate the first quadrant of the Cartesian coordinate system through identifying the coordinates of randomly generated points, or requesting that a particular point be plotted. Simple Coordinates Game is one of the Interactivate assessment explorers.\n', 'http://www.shodor.org/interactivate/activities/SimpleCoordinates/\n', 'http://www.shodor.org/media/N/G/I/3NGFiOWRkYjRlZTMyMzM5M2FiMDUzZTYwNTI1NGQ.gif\n', 'graphs,algebra,geometry\n', '3,4,5,6,7,8', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(44, 'Multi-Function Data Flyer\n', 'Enter a set of data points and a function or multiple functions, then manipulate those functions to fit those points. Manipulate the function on a coordinate plane using slider bars. Learn how each constant and coefficient affects the resulting graph.\n', 'http://www.shodor.org/interactivate/activities/MultiFunctionDataFly/\n', 'http://www.shodor.org/media/Z/j/l/jNzM4MGNlOTc3Y2ZhZDU1NzI1MGUzMzNiMDM5NmU.gif\n', 'modeling,algebra,calculus,statistics\n', '6,7,8,9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(45, 'Graph Sketcher\n', 'Students can create graphs of functions entered as algebraic expressions -- similar to a graphing calculator.\n', 'http://www.shodor.org/interactivate/activities/GraphSketcher/\n', 'http://www.shodor.org/media/N/2/N/iYTA2Nzc1YjM0NjMwYjY2Y2NhYzRjNjc5NjQwNTA.gif\n', 'graphs,algebra,calculus\n', '6,7,8,9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(46, 'Triple Venn Diagram Shape Sorter\n', 'Sort colored shapes into a three circle Venn Diagram.\n', 'http://www.shodor.org/interactivate/activities/TripleVennDiagram/\n', 'http://www.shodor.org/media/Y/m/F/lNzgzN2MwOGNlYWViYjFkNDcxZjY2YTljMDAwYzc.gif\n', 'discrete,number and operations,geometry\n', '3,4,5,6,7,8', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(47, 'Fraction Four\n', 'Students play a generalized version of connect four, gaining the chance to place a piece after simplifying fractions, converting fractions to decimals and percentages, and answering algebra questions involving fractions. Choose difficulty level, question types, and time. Fraction Four is one of the Interactivate assessment games.\n', 'http://www.shodor.org/interactivate/activities/FractionFour/\n', 'http://www.shodor.org/media/Z/D/A/3NTY3OGQ0ZjEzZmExNDY4YzA3MGU0ZTc1Y2IyMjk.gif\n', 'number and operations,algebra,fractions\n', '3,4,5,6,7,8', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(48, 'Experimental Probability\n', 'Experiment with probability using a fixed size section spinner, a variable section spinner, two regular 6-sided dice or customized dice.\n', 'http://www.shodor.org/interactivate/activities/ExpProbability/\n', 'http://www.shodor.org/media/M/j/l/mNDFjZjg2OGQzZTM1ODFhZjM4Zjk0MWU1Yjc3NDM.gif\n', 'discrete,probability,statistics\n', '3,4,5,6,7,8,9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(49, 'Tessellate!\n', 'Create a tessellation by deforming a triangle, rectangle or hexagon to form a polygon that tiles the plane. Corners of the polygons may be dragged, and corresponding edges of the polygons may be dragged. Parameters: Colors, starting polygon.\n', 'http://www.shodor.org/interactivate/activities/Tessellate/\n', 'http://www.shodor.org/media/N/j/F/iZjJiN2VmYjg3M2IzZTRlZjg4MTEwOGM1NGM1NGU.gif\n', 'geometry\n', '3,4,5,6,7,8,9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(50, 'Cross Section Flyer\n', 'Explore cross sections of different geometric solids: cone, double cone, cylinder, pyramid, and prism. Manipulate the cross section with slider bars, and see how the graphical representation changes.\n', 'http://www.shodor.org/interactivate/activities/CrossSectionFlyer/\n', 'http://www.shodor.org/media/Z/D/Q/2Yjg0Zjc5Zjg2ZmM0MTZiMTkzZWRjM2FlN2RjZDc.gif\n', 'graphs,algebra,geometry,calculus\n', '9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(51, 'Elapsed Time\n', 'Practice finding elapsed time given a starting time and an ending time. Elapsed Time is one of the Interactivate assessment explorers.\n', 'http://www.shodor.org/interactivate/activities/ElapsedTime/\n', 'http://www.shodor.org/media/Y/z/M/yOWJjOTgyMzM0NTI5N2Y3ZmVhZWJjYTRkODQyOTg.\n', 'geometry\n', '3,4,5,6,7,8', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(52, 'Possible or Not\n', 'Review the properties of functions by looking at ten different curves and deciding whether or not they meet the criteria for a graph of a function. This activity simply displays the curves - it does not quiz the user.\n', 'http://www.shodor.org/interactivate/activities/PossibleOrNot/\n', 'http://www.shodor.org/media/N/G/Q/zZDViNjgwZWFiY2RmMDVhYTFkYzIzYjIwMGJkYjg.gif\n', 'discrete,algebra\n', '6,7,8,9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(53, 'Clock Wise\n', 'Practice reading a clock, input times for the clock to display, or let the clock generate random times for you to read. Choose from three difficulty levels. Clock Wise is one of the Interactivate assessment explorers.\n', 'http://www.shodor.org/interactivate/activities/ClockWise/\n', 'http://www.shodor.org/media/M/G/I/zYTkyMTUzZDMzYjA5NTY2YzBlN2QzOTM0MmM2NDE.gif\n', 'geometry\n', '3,4,5', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(54, 'Image Tool\n', 'Measure angles, distances, and areas in several different images (choices include maps, aerial photos, and others). A scale feature allows the user to set the scale used for measuring distances and areas.\n', 'http://www.shodor.org/interactivate/activities/ImageTool/\n', 'http://www.shodor.org/media/Y/W/F/iYTY2MzNlZDU4ODI1MDUxZWViYTcxNDdkMjE1Yzc.gif\n', 'geometry\n', '3,4,5,6,7,8,9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(55, 'Fraction Quiz\n', 'Test your fraction skills by answering questions. This quiz asks you to simplify fractions, convert fractions to decimals and percentages, and answer algebra questions involving fractions. Choose difficulty level, question types, and time. Fraction Quiz is one of the Interactivate assessment quizzes.\n', 'http://www.shodor.org/interactivate/activities/FractionQuiz/\n', 'http://www.shodor.org/media/O/T/d/hZWUzMzc4YjVmZDIzZDE1YmJkNjUyMTMwOTIxOWQ.gif\n', 'number and operations,algebra,fractions\n', '3,4,5,6,7,8', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(56, 'Fire!!\n', 'Run a simulation of how a fire will spread through a stand of trees, learning about probability and chaos. Parameters: Probability that a tree catches fire if its neighbor is on fire.\n', 'http://www.shodor.org/interactivate/activities/Fire/\n', 'http://www.shodor.org/media/N/G/Q/xOGRhYTA2YzJmYTBmMzE2OWY2MWRmZjEzMzE5ZjM.gif\n', 'discrete,modeling,probability,fractions\n', '3,4,5,6,7,8,9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(57, 'Spinner\n', 'Create a game spinner with one to twelve sectors in order to look at experimental and theoretical probabilities. Parameters: Number of sectors, number of trials.\n', 'http://www.shodor.org/interactivate/activities/BasicSpinner/\n', 'http://www.shodor.org/media/M/T/d/lNGU2N2FkM2M2ZjYzOTZlM2YzNzhlM2JhODEyMDE.gif\n', 'discrete,probability,fractions,statistics\n', '3,4,5,6,7,8,9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(58, 'Equivalent Fractions Pointer\n', 'Visually represent two unique fractions that are equivalent to a given fraction. The fractional value is shown on a number line as you color in the fraction. Equivalent Fraction Pointer is one of the Interactivate assessment explorers.\n', 'http://www.shodor.org/interactivate/activities/EquivFractionPointer/\n', 'http://www.shodor.org/media/O/G/F/hNjE5OGMwMWQxZjQ4NWEzYmZjNDcwNWZhMjhkNWQ.gif\n', 'number and operations,fractions\n', '3,4,5,6,7,8', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(59, 'Cantor''s Comb\n', 'Learn about fractions between 0 and 1 by repeatedly deleting portions of a line segment, and also learn about properties of fractal objects. Parameter: fraction of the segment to be deleted each time.\n', 'http://www.shodor.org/interactivate/activities/CantorComb/\n', 'http://www.shodor.org/media/Z/j/g/5NWY4ZTMxOTFjYjBmMGU3MDVmNzE0YmJhY2FmMzg.gif\n', 'discrete,number and operations,geometry\n', '3,4,5,6,7,8,9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(60, 'Positive Linear Function Machine\n', 'Students investigate linear functions with positive slopes by trying to guess the slope and intercept from inputs and outputs. Positive Linear Function Machine is one of the Interactivate assessment explorers.\n', 'http://www.shodor.org/interactivate/activities/PositiveLinearFunct/\n', 'http://www.shodor.org/media/O/T/V/mNmY1YTk3Njk0NDk5MjQ4ODY0NTAzMDU1YjQ5NWY.gif\n', 'discrete,algebra\n', '6,7,8,9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(61, 'Another Hilbert Curve Generator\n', 'Students work step-by-step through the generation of a different Hilbert-like Curve (a fractal made from deforming a line by bending it), allowing them to explore number patterns in sequences and geometric properties of fractals.\n', 'http://www.shodor.org/interactivate/activities/AnotherHilbertCurve/\n', 'http://www.shodor.org/media/Y/z/Z/hYWVhNzlkMTNkNmZmNzNkNzMwNmYyNGJlN2M4YmM.gif\n', 'discrete,number and operations,geometry,fractions\n', '3,4,5,6,7,8,9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(62, 'Venn Diagram Shape Sorter\n', 'Sort colored shapes into a Venn diagram based on various characteristics. Venn Diagram Shape Sorter is one of the Interactivate assessment explorers.\n', 'http://www.shodor.org/interactivate/activities/ShapeSorter/\n', 'http://www.shodor.org/media/Z/W/I/0NTJmZDgwODI2ZTJiYzc1OTU0ODQ2NDgxYzc3NmE.gif\n', 'discrete,number and operations,graphs,geometry\n', '3,4,5,6,7,8', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(63, 'Tables and Chairs\n', 'Explore perimeter through rectangular and straight-line arrangements of tables, calculating the number of chairs needed to surround different arrangements. Tables and Chairs is one of the Interactivate assessment explorers.\n', 'http://www.shodor.org/interactivate/activities/Chairs/\n', 'http://www.shodor.org/media/O/D/J/jNmI0Zjk0MDcxNDE5YzEwMDgwNDlmYTJjYjA4MTc.gif\n', 'discrete,number and operations,modeling,geometry\n', '3,4,5,6,7,8', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(64, 'Number Cruncher\n', 'Similar to the original "Function Machine" but lists input and output in a table and will not let the user attempt to guess the rule without having at least two data points. Number Cruncher is one of the Interactivate assessment explorers.\n', 'http://www.shodor.org/interactivate/activities/NumberCruncher/\n', 'http://www.shodor.org/media/Y/j/F/lZDFjNDJlOTY1NjVjYmMyYzc2NTFlODA1NGUxYmE.gif\n', 'discrete,number and operations,algebra\n', '3,4,5,6,7,8,9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(65, 'General Coordinates Game\n', 'Investigate the Cartesian coordinate system through identifying the coordinates of a randomly generated point, or requesting that a particular point be plotted. General Coordinates Game is one of the Interactivate assessment explorers.\n', 'http://www.shodor.org/interactivate/activities/GeneralCoordinates/\n', 'http://www.shodor.org/media/N/j/V/lZDNjNDFjYWVkZmVhOWU0N2ViMDEwY2RhOGY2ODA.gif\n', 'algebra,geometry\n', '3,4,5,6,7,8', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(66, 'Pattern Generator\n', 'Recognize patterns in a series of shapes, numbers, or letters. After determining the pattern, the student fills in the missing pieces. Three levels of difficulty are available.\n', 'http://www.shodor.org/interactivate/activities/PatternGenerator/\n', 'http://www.shodor.org/media/O/T/c/yMWZlNmFhNTZiNjgwODQ1YTIyZTk1NmI0MDZiMGY.gif\n', 'number and operations\n', '3,4,5,6,7,8', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(67, '3D Transmographer\n', 'Build your own polygon and transform it in the Cartesian coordinate system. Experiment with reflections across any line, revolving around any line (which yields a 3-D image), rotations about any point, and translations in any direction.\n', 'http://www.shodor.org/interactivate/activities/3DTransmographer/\n', 'http://www.shodor.org/media/N/j/Z/mNDk4YjUzYmRhMjhlODE2MDA0NzA2NjExNGIxNzQ.png\n', 'graphs,algebra,geometry,calculus\n', '3,4,5,6,7,8,9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(68, 'Ordered Simple Plot\n', 'Plot ordered pairs on the graph, and they will be connected in the order that they are input. This enables you to decide how the pairs should be connected, rather than having the computer connect them from left to right.\n', 'http://www.shodor.org/interactivate/activities/OrderedSimplePlot/\n', 'http://www.shodor.org/media/Z/G/N/lODlmMTAwOThiNjRmOTY4YTUzMzI0MGYzMWNiODU.gif\n', 'graphs,algebra,geometry,statistics\n', '3,4,5,6,7,8,9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(69, 'Recursion\n', 'Graph recursive functions by defining f(0)=C and defining f(n) based on f(n-1).\n', 'http://www.shodor.org/interactivate/activities/Recursion/\n', 'http://www.shodor.org/media/M/2/M/5OTM4NGQ3NGNlMDQ3Y2EyY2VmNjVjMDMzNDI1OGQ.gif\n', 'discrete,number and operations,graphs,algebra\n', '9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(70, 'Circle Graph\n', 'Enter your own data categories and the value of each category to create a pie chart. There are also built in data sets which can be viewed.\n', 'http://www.shodor.org/interactivate/activities/CircleGraph/\n', 'http://www.shodor.org/media/N/W/M/yZjhlMjRiNzk3NzgyYzgwMmY3NmZkZjYyYmRiMGY.gif\n', 'graphs,fractions,statistics\n', '3,4,5,6,7,8,9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(71, 'Koch''s Snowflake\n', 'Step through the generation of the Koch Snowflake -- a fractal made from deforming the sides of a triangle, and explore number patterns in sequences and geometric properties of fractals.\n', 'http://www.shodor.org/interactivate/activities/KochSnowflake/\n', 'http://www.shodor.org/media/O/T/Y/3ZTViMGQ0MTliZTA4YzUxOTRiNzY4YzE1YTFhNGU.gif\n', 'discrete,number and operations,geometry,fractions\n', '3,4,5,6,7,8,9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(72, 'Dice Table\n', 'Experiment with the outcome distribution for a roll of two dice by simulating a dice throwing game. Parameters: Which player wins with which total rolled.\n', 'http://www.shodor.org/interactivate/activities/DiceTable/\n', 'http://www.shodor.org/media/M/T/Z/hM2VmYzQzMGFjODRlNjMwOGMyNDVhZjJkODA5OTQ.gif\n', 'discrete,probability,fractions\n', '6,7,8,9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(73, 'The Chaos Game\n', 'Play the Chaos Game by experimenting with probabilities. Learn about an apparently random process with a not-so-random, geometric fractal result.\n', 'http://www.shodor.org/interactivate/activities/TheChaosGame/\n', 'http://www.shodor.org/media/O/D/F/lMWM4ZWNmOTE4ZWNmMzk5MTRhODZmZjlkZDI4MDI.gif\n', 'geometry\n', '6,7,8,9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(74, 'Comparison Estimator\n', 'Compare two sets of objects, using estimation to determine which is greater. Estimate a number of objects, the length of a line, or the area of a shape. Parameter: error tolerance. Comparison Estimator is one of the Interactivate assessment explorers.\n', 'http://www.shodor.org/interactivate/activities/ComparisonEstimator/\n', 'http://www.shodor.org/media/N/m/U/5YTI4Yjc1MzAyNDdiMzVhMTBlYjJlNmIzZmIwMDc.gif\n', 'number and operations\n', '3,4,5,6,7,8,9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(75, 'Skew Distribution\n', 'Change the median and standard deviation of an automatically generated normal distribution to create a skewed distribution, allowing you to observe properties like what it means for the mean, median, and mode to be different. Parameters: median, standard deviation, number of trials, class intervals.\n', 'http://www.shodor.org/interactivate/activities/SkewDistribution/\n', 'http://www.shodor.org/media/N/m/M/3ODAyODU5NjdiOTY2Nzk0ODY2NTRjZjJiMzg1NTU.gif\n', 'graphs,statistics\n', '9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(76, 'Incline\n', 'This applet allows the user to make observations about the relationship between speed and position and how both of these are affected by initial velocity and the incline on which the biker is traveling.\n', 'http://www.shodor.org/interactivate/activities/Incline/\n', 'http://www.shodor.org/media/M/G/Y/0YmQzNzE3YTBlNDU1NTFlM2ZhN2QzMzE0MzVhZGI.gif\n', 'modeling,algebra\n', '9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(77, 'Transmographer\n', 'Explore the world of translations, reflections, and rotations in the Cartesian coordinate system by transforming squares, triangles and parallelograms. Parameters: Shape, x or y translation, x or y reflection, angle of rotation.\n', 'http://www.shodor.org/interactivate/activities/Transmographer/\n', 'http://www.shodor.org/media/Y/z/B/jZTJjZGMwMjAzODk2YmQxYTcwZWIxZjNmNjQ0NGI.gif\n', 'graphs,geometry\n', '3,4,5,6,7,8,9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(78, 'Clock Arithmetic\n', 'Work with various types of clocks in order to learn about modular arithmetic operations. Parameters: Number of hours on the clock.\n', 'http://www.shodor.org/interactivate/activities/ClockArithmetic/\n', 'http://www.shodor.org/media/Y/j/U/1Y2ZlNzlhOWE2MDQ3YTdiN2E2ODNiMGQwZWU4ZTg.gif\n', 'discrete,number and operations\n', '3,4,5,6,7,8', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(79, 'Mixtures\n', 'Mixtures allows exploration of percents through two piles of colored and uncolored chips. The user must decide how many chips to color to create the desired percentage of colored chips compared to the total pile. Mixtures is one of the Interactivate assessment explorers.\n', 'http://www.shodor.org/interactivate/activities/Mixtures/\n', 'http://www.shodor.org/media/M/D/U/wYTNhMWRjMTg5MTRmOTUyNzRmOTU4NzA0MWI4Mzg.gif\n', 'number and operations\n', '3,4,5,6,7,8,9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(80, 'Directable Fire!!\n', 'Run a simulation of how a fire will spread through a stand of trees, learning about probability and chaos. Parameters: Probability that a tree will set fire to each of its eight neighbors.\n', 'http://www.shodor.org/interactivate/activities/DirectableFire/\n', 'http://www.shodor.org/media/N/T/Q/yMjBjZTlhOTYzYTBkODA1ZjMyNzdlMThiZThhYmY.gif\n', 'discrete,modeling,probability,fractions\n', '6,7,8,9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(81, 'Bounded Fraction Finder\n', 'The same as "Bounded Fraction Pointer" but there is no arrow to help the user determine the value of a fraction between the two endpoints. Bounded Fraction Finder is one of the Interactivate assessment explorers.\n', 'http://www.shodor.org/interactivate/activities/BoundFractionFinder/\n', 'http://www.shodor.org/media/O/T/V/lNDNiMjg0MzNiN2NlMDE1ZTU1MWRiZjVjZjMwZjg.gif\n', 'number and operations,fractions\n', '3,4,5,6,7,8', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(82, 'Polar Coordinates\n', 'This activity allows the user to explore the polar coordinate system. The applet is similar to GraphIt, but instead allows users to explore the representation of a function in the polar coordinate system.\n', 'http://www.shodor.org/interactivate/activities/PolarCoordinates/\n', 'http://www.shodor.org/media/N/T/c/5NjRiOGQ3NWE0NWJhODFkZDJjZGNhMTNiYWYyZjk.png\n', 'graphs,algebra,calculus\n', '9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(83, 'Arithmetic Quiz\n', 'Arithmetic Quiz gives the user randomized questions to answer on arithmetic with whole numbers and integers. Parameters: Level of difficulty and types of questions. Arithmetic Quiz is one of the Interactivate assessment quizzes.\n', 'http://www.shodor.org/interactivate/activities/ArithmeticQuiz/\n', 'http://www.shodor.org/media/O/G/Q/5MjdjMTU0NjRhZjIwMTljN2I5ZWI1MWIxZDkxYTk.gif\n', 'discrete,number and operations,fractions\n', '3,4,5,6,7,8', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(84, 'Caesar Cipher\n', 'Create your own affine cipher for encoding and decoding messages. Input your own constant and multiplier, then input a message to encode.\n', 'http://www.shodor.org/interactivate/activities/CaesarCipher/\n', 'http://www.shodor.org/media/Z/j/B/hZTZjNjVlM2YxMTgxN2UwMjg1YWY5MGUyN2VkMjk.gif\n', 'discrete,number and operations,algebra\n', '3,4,5,6,7,8,9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(85, 'Flake Maker\n', 'Create your own fractals by drawing a "line deformation rule" and stepping through the generation of a geometric fractal. Parameters: Grid type, number of bending points on the line.\n', 'http://www.shodor.org/interactivate/activities/FlakeMaker/\n', 'http://www.shodor.org/media/Z/G/I/wNzY5ZDMzNDdjNjM4ODA3NmJjNTBjOTdlOTUxODk.gif\n', 'number and operations,geometry\n', '3,4,5,6,7,8,9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(86, 'Linear Inequalities\n', 'Students create linear inequalities and systems of linear inequalities on a coordinate plane. This is like a graphing calculator with advanced viewing options.\n', 'http://www.shodor.org/interactivate/activities/inequality/\n', 'http://www.shodor.org/media/Z/j/Q/wMTNiMWU2Nzk4NTdiMTU4MjU0NDBhZjFkMTQ3YzY.gif\n', 'algebra\n', '6,7,8,9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(87, 'Plop It!\n', 'PlopIt allows users to build dot plots of data using the mouse. View how the mean, median, and mode change as entries are added to the plot. Parameters: Range for observations.\n', 'http://www.shodor.org/interactivate/activities/PlopIt/\n', 'http://www.shodor.org/media/M/z/M/3ZjkwOGZlODA1YmQ0MzA0MjhhYzliYjc0NDlkOTk.gif\n', 'graphs,statistics\n', '3,4,5,6,7,8,9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(88, 'Two Colors Applet\n', 'Choose one of three boxes and choose one ball from the box to look at conditional probabilities. Parameters: Number of trials.\n', 'http://www.shodor.org/interactivate/activities/TwoColors/\n', 'http://www.shodor.org/media/M/D/M/2Yjk0ZDRkY2MyMjJhYmI5NGNiNGMzNTQ1ODQ4ZTM.gif\n', 'discrete,modeling,probability\n', '6,7,8,9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(89, 'Equation Solver\n', 'This activity helps you understand how to balance an equation. You input the term and the operation. The activity uses that term and operates on both sides of the equation. It then displays the resulting equation. Equation Solver is one of the Interactivate assessment explorers.\n', 'http://www.shodor.org/interactivate/activities/EquationSolver/\n', 'http://www.shodor.org/media/N/m/F/mNDE0N2JjNzNmYzk4YzA2OGNhN2NkMGY2NmJiZTc.\n', 'algebra\n', '6,7,8,9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(90, 'Stem and Leaf Plotter\n', 'View stem-and-leaf plots of your own data, and then practice finding means, medians and modes. Stem and Leaf Plotter is one of the Interactivate assessment explorers.\n', 'http://www.shodor.org/interactivate/activities/StemAndLeafPlotter/\n', 'http://www.shodor.org/media/Y/j/M/2MzQ5ZTBmZDBjYzM0ZjkwNTRlYjBkNjg0MTJhMWY.gif\n', 'graphs,statistics\n', '3,4,5,6,7,8,9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(91, 'Hilbert Curve Generator\n', 'Step through the generation of a Hilbert Curve -- a fractal made from deforming a line by bending it, and explore number patterns in sequences and geometric properties of fractals.\n', 'http://www.shodor.org/interactivate/activities/HilbertCurve/\n', 'http://www.shodor.org/media/Y/W/U/zYTRjMzhkNzE4Y2JlMzA2NDQxZmY3OWZhNDE0ZTU.gif\n', 'discrete,number and operations,geometry,fractions\n', '3,4,5,6,7,8,9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(92, 'Order of Operations Quiz\n', 'This activity allows the user to practice order of operations with addition/subtraction, multiplication/division, exponents, and parentheses. Order of Operations Quiz is one of the Interactivate assessment quizzes.\n', 'http://www.shodor.org/interactivate/activities/OperationsQuiz/\n', 'http://www.shodor.org/media/Y/z/k/zNWY4OWNiMDBjZjYwZjFjMDJjMjA5MmIzYmFjNTQ.gif\n', 'number and operations\n', '3,4,5,6,7,8,9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(93, 'Box Plot\n', 'Students can create box plots for either built-in or user-specified data as well as experiment with outliers. User may choose to use or not use the median for calculation of interquartile range.\n', 'http://www.shodor.org/interactivate/activities/BoxPlot/\n', 'http://www.shodor.org/media/Y/z/Z/jNjU0YzRmMmE5ZmE2YTZlYjRjY2U3OGY3YWEwMTA.gif\n', 'graphs,statistics\n', '6,7,8,9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(94, 'Arithmetic Four\n', 'Students play a generalized version of connect four, gaining the chance to place a piece on the board by answering arithmetic questions (addition, subtraction, multiplication, division). Parameters: time, difficulty level, types of questions. Arithmetic Four is one of the Interactivate assessment games.\n', 'http://www.shodor.org/interactivate/activities/ArithmeticFour/\n', 'http://www.shodor.org/media/O/W/Z/lYzhkYzIyYTI3MDk1MzNhZDZiYTE1Y2E4NzdmOTY.gif\n', 'discrete,number and operations,fractions\n', '3,4,5,6,7,8', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(95, 'Function Machine\n', 'Students investigate very simple functions by trying to guess the algebraic form from inputs and outputs. Function Machine is one of the Interactivate assessment explorers.\n', 'http://www.shodor.org/interactivate/activities/FunctionMachine/\n', 'http://www.shodor.org/media/M/z/A/2Yjk5ZjkyN2Q1MTgwNDM0MDBlODVmYzZkNzU0NTY.gif\n', 'discrete,algebra\n', '6,7,8,9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00');
INSERT INTO `education` (`id`, `title`, `description`, `lesson_link`, `lesson_image`, `category`, `student_grades`, `author`, `content_type`, `time_scraped`) VALUES
(96, 'Maze Game\n', 'Investigate the Cartesian coordinate system by directing a robot through a mine field laid out on the plane. Maze Game is one of the Interactivate assessment explorers.\n', 'http://www.shodor.org/interactivate/activities/MazeGame/\n', 'http://www.shodor.org/media/Z/j/N/jYzRhZWUyZjFkODY5YTRhNjBjZThhMjdiZTBjYzk.gif\n', 'graphs,algebra,geometry\n', '3,4,5,6,7,8', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(97, 'Fraction Pointer\n', 'Determine the value of two given fractions represented as points on a number line. Then find a fraction whose value is between the two given fractions (using an arrow on the number line as a guide) and determine its value. Fraction Pointer is one of the Interactivate assessment explorers.\n', 'http://www.shodor.org/interactivate/activities/FractionPointer/\n', 'http://www.shodor.org/media/N/m/Z/jYmE1Y2I2NWRjMmNiOTU2OWVkYjU5OTNiZDE5OWM.gif\n', 'number and operations,fractions\n', '3,4,5,6,7,8', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(98, 'Pie Chart\n', 'Create a pie chart, adjusting the size of the divisions using your mouse or by entering values. Parameters: Number of sections, size of sections, whether to use percents or fractions.\n', 'http://www.shodor.org/interactivate/activities/PieChart/\n', 'http://www.shodor.org/media/N/T/B/lZmU1NGFkYTM0MzZiODg0Y2Q3ZDVkOGJhOWE4YWQ.gif\n', 'graphs,statistics\n', '3,4,5,6,7,8,9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(99, 'Racing Game with Two Dice\n', 'Simulate a game where "N" players roll two dice, and the lucky player has an advantage for reaching the finish. Parameters: the number of players, number of trials and length of the race.\n', 'http://www.shodor.org/interactivate/activities/RacingGameWithTwoDie/\n', 'http://www.shodor.org/media/Z/G/M/4YTM5MzIzOWNkYjVmYmNkMzdiMGUzYTYyZjdmYmY.gif\n', 'discrete,probability\n', '6,7,8,9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(100, 'Advanced Monty Hall\n', 'Choose one of N doors to experimentally determine the odds of winning the grand prize behind one of the doors, as in the TV program "Let''s Make a Deal." Parameters: Number of doors, number of trials, staying or switching between the two remaining doors.\n', 'http://www.shodor.org/interactivate/activities/AdvancedMontyHall/\n', 'http://www.shodor.org/media/N/2/Q/5ODNhMTdhNGU2Mjc3MGY2MWFmNzE5OTI2NDhhZTE.gif\n', 'discrete,modeling,probability,statistics\n', '6,7,8,9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(101, 'Pythagorean Explorer\n', 'Calculate the length of one side of an automatically generated right triangle by using the Pythagorean Theorem, and then check your answers. Pythagorean Explorer is one of the Interactivate assessment explorers.\n', 'http://www.shodor.org/interactivate/activities/PythagoreanExplorer/\n', 'http://www.shodor.org/media/Z/j/E/5NDQ0YmQ4YTk1YjQ4NTAzZGMxMmI4ZjA5OWI3NjE.gif\n', 'geometry\n', '6,7,8,9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(102, 'Triangle Explorer\n', 'Calculate the area of a triangle drawn on a grid. Learn about areas of triangles and about the Cartesian coordinate system. Triangle Explorer is one of the Interactivate assessment explorers.\n', 'http://www.shodor.org/interactivate/activities/TriangleExplorer/\n', 'http://www.shodor.org/media/M/W/U/5MDQ4MWIyMjgyYWU5MDM4NTkwZmFkNTFjZmQzNDM.gif\n', 'geometry\n', '6,7,8,9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(103, 'Regression\n', 'Plot a bivariate data set, determine the line of best fit for their data, and then check the accuracy of your line of best fit.\n', 'http://www.shodor.org/interactivate/activities/Regression/\n', 'http://www.shodor.org/media/Y/m/F/hZjA5MTUzMzliMTNkNjI0MjUwZTU3YWVkMWU5OGQ.gif\n', 'graphs,algebra,calculus,statistics\n', '6,7,8,9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(104, 'Bounded Fraction Pointer\n', 'Determine the value of two fractions you have chosen (which are represented as points on a number line). Then find a fraction whose value is between your two fractions (using an arrow on the number line as a guide) and determine its value. Bounded Fraction Pointer is one of the Interactivate assessment explorers.\n', 'http://www.shodor.org/interactivate/activities/BoundFractionPointer/\n', 'http://www.shodor.org/media/M/T/A/3NzI3YjgzMjEwOTZkNGJiNjVkOWNkNzNlYThkODQ.gif\n', 'number and operations,fractions\n', '3,4,5,6,7,8', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(105, 'Venn Diagrams\n', 'Classify various objects into categories in a Venn Diagram. Learn how categories in Venn Diagrams work. Venn Diagrams is one of the Interactivate assessment explorers.\n', 'http://www.shodor.org/interactivate/activities/VennDiagrams/\n', 'http://www.shodor.org/media/N/j/Q/2MWJlMDkyY2NiMjc4YTgxYjA1ZDNiNmJmZWNmMDk.gif\n', 'discrete,number and operations,graphs,algebra,geometry\n', '3,4,5,6,7,8,9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(106, 'Whole Number Cruncher\n', 'Give input to the Whole Number Cruncher and try to guess what it did from the output it generates. This activity only generates multiplication and addition functions to avoid outputting any negative numbers. Whole Number Cruncher is one of the Interactivate assessment explorers.\n', 'http://www.shodor.org/interactivate/activities/WholeNumberCruncher/\n', 'http://www.shodor.org/media/M/z/k/5Yzk3NGYyODgyODQxZWYzMDAyZjlhNGEyNTVhNGQ.gif\n', 'discrete,number and operations,algebra\n', '3,4,5,6,7,8,9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(107, 'Shape Explorer\n', 'Learn the relationship between perimeter and area. A random shape will be automatically generated. Calculate the area and perimeter of this shape. Shape Explorer is one of the Interactivate assessment explorers.\n', 'http://www.shodor.org/interactivate/activities/ShapeExplorer/\n', 'http://www.shodor.org/media/O/G/V/mZDAwZDM3OGY4OTY4NGYxNDBiY2EyZGY4OTE3MmI.gif\n', 'geometry\n', '3,4,5,6,7,8', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(108, 'Sierpinski''s Carpet\n', 'Step through the generation of Sierpinski''s Carpet -- a fractal made from subdividing a square into nine smaller squares and cutting the middle one out. Explore number patterns in sequences and geometric properties of fractals.\n', 'http://www.shodor.org/interactivate/activities/SierpinskiCarpet/\n', 'http://www.shodor.org/media/Z/j/Y/4NGYzZTBhZGIyOWY4ZTNmZjZmOTdmMzJhNGYxODU.gif\n', 'discrete,number and operations,geometry,fractions\n', '3,4,5,6,7,8,9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(109, 'Elapsed Time Two\n', 'Given a starting time and elapsed time practice finding the ending time. Elapsed Time Two is one of the Interactivate assessment explorers.\n', 'http://www.shodor.org/interactivate/activities/ElapsedTimeTwo/\n', 'http://www.shodor.org/media/N/D/Q/yY2Y3MDViZTllNGExMGVlMzA0MGJmM2I1MmQxYTc.png\n', 'geometry\n', '3,4,5,6,7,8', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(110, 'Coloring Remainders in Pascal''s Triangle\n', 'Color numbers in Pascal''s Triangle by rolling a number and then clicking on all entries that have the same remainder when divided by the number rolled, thereby practicing division and remainders, investigating number patterns, and investigating fractal patterns. Coloring Remainders in Pascal''s Triangle is one of the Interactivate assessment explorers.\n', 'http://www.shodor.org/interactivate/activities/ColoringRemainder/\n', 'http://www.shodor.org/media/M/W/I/wOTgzZTZlYWRkZDA5MWFjYmRkMzk4ZWMwMTY0Zjk.gif\n', 'discrete,number and operations,geometry,fractions\n', '3,4,5,6,7,8,9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(111, 'Single Fraction Finder\n', 'Determine the value of a given fraction represented as a point on a number line. Then find a fraction whose value is a given fraction. Fraction Pointer is one of the Interactivate assessment explorers.\n', 'http://www.shodor.org/interactivate/activities/SingleFractionFinder/\n', 'http://www.shodor.org/media/M/W/U/wMWJmYTY4YjkzNTQ3YTdjNWNjYTBlODY5OTBmZGU.gif\n', 'number and operations,fractions\n', '3,4,5,6,7,8', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(112, 'Life\n', 'Run the classic game of life, learning about probabilities, chaos and simulation. This activity allows the user to run a randomly generated world or test out various patterns. This is a very powerful activity with a wide range of options. It runs in a separate window.\n', 'http://www.shodor.org/interactivate/activities/Life/\n', 'http://www.shodor.org/media/N/G/M/1MDgxODdlMWViMjIxMjU3NGMwOWE5ZTE4YzRmMTY.gif\n', 'modeling,probability\n', '6,7,8,9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(113, 'Spread of Disease\n', 'Models how a population of susceptible, infected, and recovered people is affected by a disease.\n', 'http://www.shodor.org/interactivate/activities/SpreadofDisease/\n', 'http://www.shodor.org/media/Z/W/Q/1ZGQ5Y2EzNDVkZDczNmRkYTI0MWFhN2FjN2I3ZmI.png\n', 'modeling,probability\n', '3,4,5,6,7,8,9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(114, 'Scatter Plot\n', 'Graph ordered pairs and customize the graph title and axis labels. Points are connected from left to right, rather than being connected in the order they are entered.\n', 'http://www.shodor.org/interactivate/activities/ScatterPlot/\n', 'http://www.shodor.org/media/M/D/U/3YzUzZTEzNGRjZTVlZDk4NmUxMDIzYmI2ODU1MTY.gif\n', 'graphs,algebra,statistics\n', '3,4,5,6,7,8,9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(115, 'Multi Bar Graph\n', 'Enter data to create a double bar graph, then manipulate the graph''s maximum and minimum values.\n', 'http://www.shodor.org/interactivate/activities/MultiBarGraph/\n', 'http://www.shodor.org/media/N/m/J/lOWIxYjFmNTNmMTJkY2UzOTg4YTJkNzJjNDZhNTQ.gif\n', 'graphs,statistics\n', '6,7,8,9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(116, 'Parametric GraphIt\n', 'This activity allows the user to plot ordered pairs and parametric equations on the same coordinate plane. The applet is similar to GraphIt, but instead allows users to explore the parametric representation of a function.\n', 'http://www.shodor.org/interactivate/activities/ParametricGraphIt/\n', 'http://www.shodor.org/media/M/T/E/2NDg2OTQzZTE1NWZmZTFmNjUwNWI3ZGNmNjlkYWM.png\n', 'calculus\n', '9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(117, 'Area Explorer\n', 'Learn the relationship between perimeter and area. A shape will be automatically generated with the perimeter that you choose. Calculate the area of this shape. Area Explorer is one of the Interactivate assessment explorers.\n', 'http://www.shodor.org/interactivate/activities/AreaExplorer/\n', 'http://www.shodor.org/media/O/D/Q/2NDlmODVmN2VkZDk5ZDAyZTI4MGNmMjJmNzA3Nzc.gif\n', 'geometry\n', '3,4,5,6,7,8', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(118, 'Fire Assessment\n', 'Learn about estimation through modeling of a forest fire. This activity allows the user to burn a virtual forest, then estimate the number, the percent, or the fraction of trees burned. Fire Assessment is one of the Interactivate assessment explorers.\n', 'http://www.shodor.org/interactivate/activities/FireAssessment/\n', 'http://www.shodor.org/media/Y/T/A/5OTljMjUzZTkxYmJkNjliM2I0OGQ2ZTM5Y2VhMzU.gif\n', 'number and operations,modeling,probability\n', '3,4,5,6,7,8,9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(119, 'Data Flyer\n', 'Enter a set of data points, then derive a function to fit those points. Manipulate the function on a coordinate plane using slider bars. Learn how each constant and coefficient affects the resulting graph.\n', 'http://www.shodor.org/interactivate/activities/DataFlyer/\n', 'http://www.shodor.org/media/M/z/d/lZDk0NmI3YjMzNGVkYjMwYmUyYjYyYWVjMGIxMTU.gif\n', 'graphs,modeling,algebra,statistics\n', '6,7,8,9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(120, 'Fraction Finder\n', 'Determine the value of two given fractions represented as points on a number line. Then find a fraction whose value is between the two given fractions and determine its value. Fraction Finder is one of the Interactivate assessment explorers.\n', 'http://www.shodor.org/interactivate/activities/FractionFinder/\n', 'http://www.shodor.org/media/Z/G/Y/5MzJiNDZlNWNkOGNlYmE2YjhjMzliODNiNTNiOWY.gif\n', 'number and operations,fractions\n', '3,4,5,6,7,8', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(121, 'Function Flyer\n', 'A more advanced version of Slope Slider, this activity allows the manipulation of the constants and coefficients in any function thereby encouraging the user to explore the effects on the graph of the function by changing those numbers.\n', 'http://www.shodor.org/interactivate/activities/FunctionFlyer/\n', 'http://www.shodor.org/media/Z/j/A/3NDE2YmVlN2YzN2M3N2Q2Yjk3ZDRmYTNhNDUzOTI.gif\n', 'graphs,algebra,calculus\n', '6,7,8,9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(122, 'Fractured Pictures\n', 'Generate complicated geometric fractals by specifying starting polygon and scale factor.\n', 'http://www.shodor.org/interactivate/activities/FracturedPictures/\n', 'http://www.shodor.org/media/M/D/k/wOTg3YWZiZGQxYzU2ZjE2MGU2ZDc3YzExOWZhZTk.gif\n', 'discrete,geometry\n', '6,7,8,9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(123, 'Life Lite\n', 'Run the classic game of life, learning about probabilities, chaos and simulation. This activity allows the user to run a randomly generated world or test out various patterns. This is a simple activity which runs directly in the Interactivate window.\n', 'http://www.shodor.org/interactivate/activities/LifeLite/\n', 'http://www.shodor.org/media/Z/D/k/wZTY0NWQxOTQyYTBhMjdjYWVjMWNiYTI1YTdmOWI.gif\n', 'modeling,probability\n', '6,7,8,9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(124, 'Transmographer 2\n', 'Build your own polygon and transform it in the Cartesian coordinate system. Experiment with reflections across any line, rotations about any point, and translations in any direction. Parameters: Shape, x or y translation, x or y reflection, angle of rotation\n', 'http://www.shodor.org/interactivate/activities/TransmographerTwo/\n', 'http://www.shodor.org/media/N/G/Z/lYzVhYjVjYzA4Zjk2MWVkNTRhMTA5ZTc0YTJjNWE.gif\n', 'graphs,geometry\n', '3,4,5,6,7,8,9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(125, 'Marbles\n', 'Learn about sampling with and without replacement by randomly drawing marbles from a bag. Parameters: Number and color of marbles in the bag, replacement rule.\n', 'http://www.shodor.org/interactivate/activities/Marbles/\n', 'http://www.shodor.org/media/N/m/N/kM2FhYTNhYTVjMWVjZDVmYjliMDIwMWY5ZTBlNDc.gif\n', 'discrete,probability\n', '6,7,8,9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(126, 'Graphit\n', 'Create graphs of functions and sets of ordered pairs on the same coordinate plane. This is like a graphing calculator with advanced viewing options.\n', 'http://www.shodor.org/interactivate/activities/Graphit/\n', 'http://www.shodor.org/media/Z/W/Y/1NDcwYzc2OTk1N2QzN2I4Mzg1NmZmYTMwNTY0MmI.gif\n', 'graphs,algebra,calculus,statistics\n', '6,7,8,9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(127, 'Coloring Multiples in Pascal''s Triangle\n', 'Color numbers in Pascal''s Triangle by rolling a number and then clicking on all entries that are multiples of the number rolled, thereby practicing multiplication tables, investigating number patterns, and investigating fractal patterns. Coloring Multiples in Pascal''s Triangle is one of the Interactivate assessment explorers.\n', 'http://www.shodor.org/interactivate/activities/ColoringMultiples/\n', 'http://www.shodor.org/media/M/2/Z/mNmMxZTNiMDRiZTJlZjFhZDk0NjYzMjViZWMyYjE.gif\n', 'discrete,number and operations,geometry,fractions\n', '3,4,5,6,7,8,9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(128, 'Factorize\n', 'Visualize factors through building rectangular areas on a grid. First enter all the factorizations of a number, then draw each factor set as an area on the grid. Factorize is one of the Interactivate assessment explorers.\n', 'http://www.shodor.org/interactivate/activities/Factorize/\n', 'http://www.shodor.org/media/O/D/E/3YzlhZTNjZmIxYzI1ZGZkNzkwMjBlMmE3MGM3MjQ.gif\n', 'discrete,number and operations,geometry,fractions\n', '3,4,5,6,7,8,9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(129, 'The Mandelbrot Set\n', 'Explore fractals by investigating the relationships between the Mandelbrot set and Julia sets.\n', 'http://www.shodor.org/interactivate/activities/TheMandelbrotSet/\n', 'http://www.shodor.org/media/N/G/U/1NzQ4NWEzYmI0YWQ1NTk4NGJiZmIwZjYzZjMzODA.gif\n', 'discrete,number and operations,geometry,fractions\n', '6,7,8,9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(130, 'Estimator Four\n', 'Play a "Connect-Four" style game, earning a game piece each time you answer an estimation question correctly. This game asks the players to estimate the answer to addition, multiplication, and percentage questions. Choose difficulty level, question types, and time. Estimator Four is one of the Interactivate assessment games.\n', 'http://www.shodor.org/interactivate/activities/EstimatorFour/\n', 'http://www.shodor.org/media/Z/m/I/zMTdmMjc4NmI1MGIwMTdmN2JmNzMxNjUyNGNjNzY.gif\n', 'number and operations\n', '3,4,5,6,7,8,9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(131, 'Fraction Sorter\n', 'Visualize fractions by coloring in the appropriate portions of either a circle or a square, then order those fractions from least to greatest. Fraction Sorter is one of the Interactivate assessment explorers.\n', 'http://www.shodor.org/interactivate/activities/FractionSorter/\n', 'http://www.shodor.org/media/O/W/E/1NTY0M2ExYmE3NTc1NmQ5NTQ5ZDBiNzBkZDU5ZTA.gif\n', 'number and operations,fractions\n', '3,4,5,6,7,8', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(132, 'Simple Plot\n', 'Plot ordered pairs of numbers, either as a scatter plot or with the dots connected. Points are connected from right to left, rather than being connected in the order they are entered.\n', 'http://www.shodor.org/interactivate/activities/SimplePlot/\n', 'http://www.shodor.org/media/Z/j/k/0OTE4ZTQwYzAyNTM3YzM5Njg1MTA2OGRjMzAxMmY.gif\n', 'graphs,algebra,geometry,statistics\n', '3,4,5,6,7,8,9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(133, 'InteGreat!\n', 'InteGreat! allows the user to visually explore the idea of integration through approximating the integral value with partitions. The user controls the number of partitions, the upper and lower limits, and the method used to estimate the integral.\n', 'http://www.shodor.org/interactivate/activities/Integrate/\n', 'http://www.shodor.org/media/M/W/J/kZDJjZGVlNGExYTBhODM2YWQ1NjhjMTE1ZDdkNzc.gif\n', 'graphs,algebra,calculus\n', '9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(134, 'Equivalent Fractions Finder\n', 'Visually represent two unique fractions that are equivalent to a given fraction. The fractional value is shown on a number line after you check to see if your fraction is correct. Equivalent Fraction Finder is one of the Interactivate assessment explorers.\n', 'http://www.shodor.org/interactivate/activities/EquivFractionFinder/\n', 'http://www.shodor.org/media/N/T/E/0YmY3ZTIyZWI4YjQxYTRhM2RmMjAzNjcyYjk4YTA.gif\n', 'number and operations,fractions\n', '3,4,5,6,7,8', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(135, 'Slope Slider\n', 'Similar to other "flyers", Slope Slider uses slider bars to explore the effect of the multiplier and constant on a linear function of the form f(x)=mx+b. Explore the relationship between slope and intercept in the Cartesian coordinate system.\n', 'http://www.shodor.org/interactivate/activities/SlopeSlider/\n', 'http://www.shodor.org/media/N/m/Y/3Y2MyMzI3NWRjOTE5MmNmYWRlMWE0ODY5MGE0Zjc.gif\n', 'graphs,algebra\n', '6,7,8,9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(136, 'Sierpinski''s Triangle\n', 'Step through the generation of Sierpinski''s Triangle -- a fractal made from subdividing a triangle into four smaller triangles and cutting the middle one out. Explore number patterns in sequences and geometric properties of fractals.\n', 'http://www.shodor.org/interactivate/activities/SierpinskiTriangle/\n', 'http://www.shodor.org/media/N/2/Q/zYzYzZDhiM2IyZDJmNjY3MTNlOTA3NmFmODIzOWQ.gif\n', 'discrete,number and operations,geometry,fractions\n', '3,4,5,6,7,8,9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(137, 'Adjustable Spinner\n', 'Create a game spinner with variable sized sectors to look at experimental and theoretical probabilities. Parameters: Sizes of sectors, number of sectors, number of trials.\n', 'http://www.shodor.org/interactivate/activities/AdjustableSpinner/\n', 'http://www.shodor.org/media/M/z/h/kYzBlNDQ1YTVjMDZlNjg0Mzc4ZGMzMDZhYmU3MmI.gif\n', 'discrete,probability,fractions,statistics\n', '3,4,5,6,7,8,9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(138, 'Number Base Clocks\n', 'Visually explore counting and place value with different number bases, from base 2 to base 16, and up to the hundreds place using a clock like interface. The activity also allows you to look at the numbers on the clock in base 10 or in your other chosen base to explore the relationship between those values.\n', 'http://www.shodor.org/interactivate/activities/NumberBaseClocks/\n', 'http://www.shodor.org/media/N/G/Y/xMTljZDdiZjNjZTBkZmY5ZWE3ODQ3NzQ0YzhkOGI.gif\n', 'discrete,number and operations\n', '3,4,5,6,7,8,9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(139, 'Fitted Normal Distribution\n', 'This applet allows the user to experiment with randomly generated data sets at various sample sizes and standard deviations. Then, users can compare the distribution of the experimental data to the expected distribution.\n', 'http://www.shodor.org/interactivate/activities/FittedNormalDistr/\n', 'http://www.shodor.org/media/N/T/I/yY2VlMGJmZjRmZTg0ZjIyMjRlOTNhNmFjMTA5NjM.png\n', 'statistics\n', '9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(140, 'Sequencer\n', 'Learn about number patterns in sequences and recursions by specifying a starting number, multiplier, and add-on. The numbers in the sequence are displayed on a graph, and they are also listed below the graph.\n', 'http://www.shodor.org/interactivate/activities/Sequencer/\n', 'http://www.shodor.org/media/Y/2/R/iOWE3ODA5ZTM4ZjY5ZWJjYTYyM2UyMTBiZGI4YjA.gif\n', 'discrete,number and operations,graphs,algebra\n', '6,7,8,9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(141, 'Function Revolution\n', 'This activity allows the user to find the volume and surface area of various functions as they are rotated around axes. This applet can be used to practice finding integrals using the disk and washer methods of calculating volume.\n', 'http://www.shodor.org/interactivate/activities/FunctionRevolution/\n', 'http://www.shodor.org/media/N/2/Q/3MjNmN2VmODIzODVjMjA3YWJkNDU2NTdjNmZlODU.png\n', 'calculus\n', '9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00'),
(142, 'Normal Distribution\n', 'Change the standard deviation of an automatically generated normal distribution to create a new histogram. Observe how well the histogram fits the curve, and how areas under the curve correspond to the number of trials. Parameters: standard deviation, number of trials, class intervals.\n', 'http://www.shodor.org/interactivate/activities/NormalDistribution/\n', 'http://www.shodor.org/media/N/D/g/4ODBiMGVkYWNhODg3N2QyZDQyZTY3MGQ4NjMzNGM.gif\n', 'graphs,statistics\n', '9,10,11,12', 'Shodor Education Foundation, Inc.\n', 'interactive lesson\n', '2015-04-22 23:55:00');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `education`
--
ALTER TABLE `education`
 ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `education`
--
ALTER TABLE `education`
MODIFY `id` int(5) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=143;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
